version: '3.8'

services:
  nest-app:
    container_name: encurtador-url-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./db:/app/db
    env_file:
      - .env
    command: npm run start:dev